// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY50GWCgRbRNEWuDCIgbj8W4PBdj_8czo',
    appId: '1:127707562196:android:19a69af79876e87e23fb41',
    messagingSenderId: '127707562196',
    projectId: 'simple-domain-app',
    storageBucket: 'simple-domain-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADE37Mjgx4bveZsz9iWgs_Ztm9AQPvB_Q',
    appId: '1:127707562196:web:154b97b57126df9c23fb41',
    messagingSenderId: '127707562196',
    projectId: 'simple-domain-app',
    authDomain: 'simple-domain-app.firebaseapp.com',
    storageBucket: 'simple-domain-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbZyskDkdeDgPR_xNShcKcyOiHiUMIQQI',
    appId: '1:127707562196:ios:8ce809d0bb79a33123fb41',
    messagingSenderId: '127707562196',
    projectId: 'simple-domain-app',
    storageBucket: 'simple-domain-app.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbZyskDkdeDgPR_xNShcKcyOiHiUMIQQI',
    appId: '1:127707562196:ios:8ce809d0bb79a33123fb41',
    messagingSenderId: '127707562196',
    projectId: 'simple-domain-app',
    storageBucket: 'simple-domain-app.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADE37Mjgx4bveZsz9iWgs_Ztm9AQPvB_Q',
    appId: '1:127707562196:web:a18d224dd8e8b9d023fb41',
    messagingSenderId: '127707562196',
    projectId: 'simple-domain-app',
    authDomain: 'simple-domain-app.firebaseapp.com',
    storageBucket: 'simple-domain-app.firebasestorage.app',
  );

}